name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: npm install

    - name: Generate Sitemap
      run: |
        npm install -g sitemap-generator
        sitemap-generator --config sitemap-config.json > sitemap.xml

    - name: Commit Changes
      run: |
        git config --global user.name 'your_username'
        git config --global user.email 'your_email'
        git add sitemap.xml
        git commit -m "Update sitemap.xml"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN